# Generated by Django 4.2.7 on 2023-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
